# Generated by Django 4.1.7 on 2023-02-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlideId', models.CharField(max_length=10)),
                ('PageNo', models.IntegerField()),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=500)),
            ],
        ),
    ]
