# Generated by Django 4.1.7 on 2023-03-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideque',
            name='Slide',
            field=models.FileField(blank=True, upload_to='slides'),
        ),
    ]
